// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGemc4su8vhafFJ4Y_nH0KERUptPoLRM0',
    appId: '1:399624615138:web:a7da05db4cb10babe6dabb',
    messagingSenderId: '399624615138',
    projectId: 'hamza-chat-app',
    authDomain: 'hamza-chat-app.firebaseapp.com',
    storageBucket: 'hamza-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQbITEj6tceAMxBqhAnABaW7Et1m9ZZX8',
    appId: '1:399624615138:android:4a23ae3c7e4f54a7e6dabb',
    messagingSenderId: '399624615138',
    projectId: 'hamza-chat-app',
    storageBucket: 'hamza-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTybsQL6r_tR6vib7fpuiExvxRgGBWtgU',
    appId: '1:399624615138:ios:4c02311c1a3041fde6dabb',
    messagingSenderId: '399624615138',
    projectId: 'hamza-chat-app',
    storageBucket: 'hamza-chat-app.appspot.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTybsQL6r_tR6vib7fpuiExvxRgGBWtgU',
    appId: '1:399624615138:ios:4c02311c1a3041fde6dabb',
    messagingSenderId: '399624615138',
    projectId: 'hamza-chat-app',
    storageBucket: 'hamza-chat-app.appspot.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGemc4su8vhafFJ4Y_nH0KERUptPoLRM0',
    appId: '1:399624615138:web:6a155522adeb4a9ce6dabb',
    messagingSenderId: '399624615138',
    projectId: 'hamza-chat-app',
    authDomain: 'hamza-chat-app.firebaseapp.com',
    storageBucket: 'hamza-chat-app.appspot.com',
  );
}
